### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1, 100, 15)
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
b = np.random.randint(1,100, 24).reshape(6,4)
b

array([[19, 61, 26, 95],
       [15, 91, 14, 50],
       [69, 53, 69, 54],
       [57, 57,  2, 67],
       [70, 70, 26, 48],
       [71, 85, 87, 70]])

In [ ]:
np.sort(a)

array([ 6,  6, 17, 19, 23, 34, 40, 52, 60, 67, 71, 75, 84, 89, 97])

In [ ]:
np.sort(a)[::-1]

array([97, 89, 84, 75, 71, 67, 60, 52, 40, 34, 23, 19, 17,  6,  6])

In [ ]:
np.sort(b)

array([[19, 26, 61, 95],
       [14, 15, 50, 91],
       [53, 54, 69, 69],
       [ 2, 57, 57, 67],
       [26, 48, 70, 70],
       [70, 71, 85, 87]])

In [ ]:
np.sort(b, axis = 0)

array([[15, 53,  2, 48],
       [19, 57, 14, 50],
       [57, 61, 26, 54],
       [69, 70, 26, 67],
       [70, 85, 69, 70],
       [71, 91, 87, 95]])

In [ ]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
x = np.array(values, dtype=dtype)       # create a structured array
np.sort(x, order='height')


array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [ ]:
np.sort(x, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a, 200)

array([  6,  23,  40,  60,  17,  52,  19,   6,  67,  34,  97,  71,  84,
        89,  75, 200])

In [ ]:
b

array([[19, 61, 26, 95],
       [15, 91, 14, 50],
       [69, 53, 69, 54],
       [57, 57,  2, 67],
       [70, 70, 26, 48],
       [71, 85, 87, 70]])

In [ ]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[19., 61., 26., 95.,  1.],
       [15., 91., 14., 50.,  1.],
       [69., 53., 69., 54.,  1.],
       [57., 57.,  2., 67.,  1.],
       [70., 70., 26., 48.,  1.],
       [71., 85., 87., 70.,  1.]])

In [ ]:
b.shape[0]  # 0 for column

6

In [ ]:
b.shape[1]

4

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[19.        , 61.        , 26.        , 95.        ,  0.19368742],
       [15.        , 91.        , 14.        , 50.        ,  0.95928355],
       [69.        , 53.        , 69.        , 54.        ,  0.9614195 ],
       [57.        , 57.        ,  2.        , 67.        ,  0.86761674],
       [70.        , 70.        , 26.        , 48.        ,  0.24711462],
       [71.        , 85.        , 87.        , 70.        ,  0.91790153]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2, 3)
d = np.arange(6,12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.expand_dims(a, axis=0).shape

(1, 15)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 3,  5,  8, 10, 11, 12, 13, 14]),)

In [ ]:
# replace all values > 5- with 0
# np.where(condition, true, false)

np.where(a > 50, 0, a )

array([ 6, 23, 40,  0, 17,  0, 19,  6,  0, 34,  0,  0,  0,  0,  0])

In [ ]:
np.where(a%2 == 0, 0, a)

array([ 0, 23,  0,  0, 17,  0, 19,  0, 67,  0, 97, 71,  0, 89, 75])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.argmax(a)

10

In [ ]:
b

array([[19, 61, 26, 95],
       [15, 91, 14, 50],
       [69, 53, 69, 54],
       [57, 57,  2, 67],
       [70, 70, 26, 48],
       [71, 85, 87, 70]])

In [ ]:
np.argmax(b, axis=0)

array([5, 1, 5, 0])

In [ ]:
np.argmax(b, axis=1)


array([3, 1, 0, 3, 0, 2])

In [ ]:
# np.argmin
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.cumsum(a)

array([  6,  29,  69, 129, 146, 198, 217, 223, 290, 324, 421, 492, 576,
       665, 740])

In [ ]:
b

array([[19, 61, 26, 95],
       [15, 91, 14, 50],
       [69, 53, 69, 54],
       [57, 57,  2, 67],
       [70, 70, 26, 48],
       [71, 85, 87, 70]])

In [ ]:
np.cumsum(b, axis = 0)

array([[ 19,  61,  26,  95],
       [ 34, 152,  40, 145],
       [103, 205, 109, 199],
       [160, 262, 111, 266],
       [230, 332, 137, 314],
       [301, 417, 224, 384]])

In [ ]:
np.cumsum(b, axis = 1)

array([[ 19,  80, 106, 201],
       [ 15, 106, 120, 170],
       [ 69, 122, 191, 245],
       [ 57, 114, 116, 183],
       [ 70, 140, 166, 214],
       [ 71, 156, 243, 313]])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  6,                 138,                5520,
                    331200,             5630400,           292780800,
                5562835200,         33377011200,       2236259750400,
            76032831513600,    7375184656819200,  523638110634163200,
       7092113145850605568, 4008771474579140608, 5509955414082719744])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.percentile(a, 100)

97.0

In [ ]:
np.percentile(a, 50)

52.0

In [ ]:
np.median(a)

52.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 1, 1, 1, 2, 2, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

 ### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a, items)

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.flip(a) # mirror image

array([75, 89, 84, 71, 97, 34, 67,  6, 19, 52, 17, 60, 40, 23,  6])

In [ ]:
b

array([[19, 61, 26, 95],
       [15, 91, 14, 50],
       [69, 53, 69, 54],
       [57, 57,  2, 67],
       [70, 70, 26, 48],
       [71, 85, 87, 70]])

In [ ]:
np.flip(b)

array([[70, 87, 85, 71],
       [48, 26, 70, 70],
       [67,  2, 57, 57],
       [54, 69, 53, 69],
       [50, 14, 91, 15],
       [95, 26, 61, 19]])

In [ ]:
np.flip(b, axis = 0)

array([[71, 85, 87, 70],
       [70, 70, 26, 48],
       [57, 57,  2, 67],
       [69, 53, 69, 54],
       [15, 91, 14, 50],
       [19, 61, 26, 95]])

In [ ]:
np.flip(b, axis = 1)

array([[95, 26, 61, 19],
       [50, 14, 91, 15],
       [54, 69, 53, 69],
       [67,  2, 57, 57],
       [48, 26, 70, 70],
       [70, 87, 85, 71]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
a

array([ 6, 23, 40, 60, 17, 52, 19,  6, 67, 34, 97, 71, 84, 89, 75])

In [ ]:
np.put(a, [0,1], [345,456])

In [ ]:
a

array([345, 456,  40,  60,  17,  52, 345,   6,  67,  34,  97,  71,  84,
        89,  75])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
a

array([345, 456,  40,  60,  17,  52, 345,   6,  67,  34,  97,  71,  84,
        89,  75])

In [ ]:
np.delete(a, 1)

array([345,  40,  60,  17,  52, 345,   6,  67,  34,  97,  71,  84,  89,
        75])

In [ ]:
np.delete(a,[2,4,6])

array([345, 456,  60,  52,   6,  67,  34,  97,  71,  84,  89,  75])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
np.in1d(m,2)

array([False,  True, False, False, False])

In [ ]:
m[np.in1d(m,2)]

array([2])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([345, 456,  40,  60,  17,  52, 345,   6,  67,  34,  97,  71,  84,
        89,  75])

In [ ]:
np.clip(a, a_min = 25, a_max = 75)

array([75, 75, 40, 60, 25, 52, 75, 25, 67, 34, 75, 71, 75, 75, 75])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform


In [ ]:
# 19. np.count_nonzero


In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:
# 25. np.allclose and equals