### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(type(a)) # vector

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 2d and 3d
b = np.array([[1,2,3],[4,5,6]])
print(b)  # matrice

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(c)    # tensor

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# dtype
np.array([1,2,3,4], dtype=float)


array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4], dtype=bool)


array([ True,  True,  True,  True])

In [ ]:
np.array([1,2,3,4], dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
# np.arange
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a = np.arange(1,11,2)
print(a)


[1 3 5 7 9]


In [ ]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.58048984, 0.30106955, 0.53473369, 0.36794426],
       [0.63602504, 0.25298145, 0.98376407, 0.66928014],
       [0.76905904, 0.95667593, 0.00163727, 0.20758878]])

In [ ]:
# np.linspace
np.linspace(-10,10,10) # generate points on equadistant

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.linspace(-1000,1000,100, dtype=int)

array([-1000,  -980,  -960,  -940,  -920,  -899,  -879,  -859,  -839,
        -819,  -798,  -778,  -758,  -738,  -718,  -697,  -677,  -657,
        -637,  -617,  -596,  -576,  -556,  -536,  -516,  -495,  -475,
        -455,  -435,  -415,  -394,  -374,  -354,  -334,  -314,  -293,
        -273,  -253,  -233,  -213,  -192,  -172,  -152,  -132,  -112,
         -91,   -71,   -51,   -31,   -11,    10,    30,    50,    70,
          90,   111,   131,   151,   171,   191,   212,   232,   252,
         272,   292,   313,   333,   353,   373,   393,   414,   434,
         454,   474,   494,   515,   535,   555,   575,   595,   616,
         636,   656,   676,   696,   717,   737,   757,   777,   797,
         818,   838,   858,   878,   898,   919,   939,   959,   979,
        1000])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim = > telldimension
a1.ndim

1

In [ ]:
print(a2.ndim)
print(a3.ndim)


2
3


In [ ]:
# shape
a3.shape # first 2 determine how many 2d array and second , third 2 determine row and column

(2, 2, 2)

In [ ]:
print(a2.shape)
print(a1.shape)

(3, 4)
(10,)


In [ ]:
# size = total no. of item
a3.size

8

In [ ]:
print(a2.size)
print(a1.size)


12
10


In [ ]:
# itemsize tell memory kitns sotrage le rha hai
a3.itemsize

8

In [ ]:
print(a2.itemsize)
print(a1.itemsize)


8
8


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [ ]:
a1 = np.arange(11, dtype=np.int32)
print(a1.itemsize)
print(a1.dtype)

4
int32


### Changing  Datatype



In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

In [ ]:
print(a1)
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operations

# arithmetric
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1 # not any change occur after arithimetic operation

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# relational
a2 > 18

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Function

In [ ]:

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[66., 99., 45.],
       [78., 36.,  7.],
       [ 4., 97., 45.]])

In [ ]:
# max
np.max(a1)

99.0

In [ ]:
# min
np.min(a1)

4.0

In [ ]:
np.sum(a1)

477.0

In [ ]:
np.prod(a1)

100909261252800.0

In [ ]:
np.product(a1)

100909261252800.0

In [ ]:
# hr row k minimum value
# 0 =-> column
# 1 -> row
np.min(a1, axis=0)

array([ 4., 36.,  7.])

In [ ]:
np.min(a1, axis=1)

array([45.,  7.,  4.])

In [ ]:
np.max(a1, axis = 1)

array([99., 78., 97.])

In [ ]:
np.max(a1, axis = 0)

array([78., 99., 45.])

In [ ]:
np.prod(a1, axis=0)

array([ 20592., 345708.,  14175.])

In [ ]:
# max/median/std/var

np.mean(a1)

53.0

In [ ]:
np.mean(a1, axis = 0)

array([49.33333333, 77.33333333, 32.33333333])

In [ ]:
np.median(a1, axis = 1)

array([66., 36., 45.])

In [ ]:
np.var(a1, axis = 0)

array([1051.55555556,  854.88888889,  320.88888889])

In [ ]:
np.sin(a1)

array([[-0.02655115, -0.99920683,  0.85090352],
       [ 0.51397846, -0.99177885,  0.6569866 ],
       [-0.7568025 ,  0.37960774,  0.85090352]])

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
# dot product
a1 = np.arange(1,13).reshape(3,4)
a2 = np.arange(13,25).reshape(4,3)

In [ ]:
a2

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [ ]:
# log and exponents
np.log(a1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [ ]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [ ]:
# round/floor/ceil

np.floor(np.random.random((2,3))*100)

array([[80., 23., 48.],
       [45., 31.,  9.]])

In [ ]:
np.round(np.random.random((3,4))*10)

array([[2., 2., 0., 3.],
       [8., 2., 9., 2.],
       [0., 4., 9., 5.]])

In [ ]:
np.ceil(np.random.random((2,3))*20)

array([[15.,  8., 12.],
       [15., 18., 13.]])

### Indexing and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(2,2,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

9

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

6

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a3[1,1,2]

11

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:1]

array([[0, 1, 2, 3]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[0::2, 0::3] # [row, column]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1:2, 0::3]

array([[4, 7]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0, 1,]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in a3:
  for j in i:
    print(j)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]


In [ ]:
for i in a3:
  for j in i:
    for k in j:
      print(k, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [ ]:
for i in np.nditer(a3):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

### Reshaping

In [ ]:
# reshape

In [ ]:
# transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel == convert into 1d array

In [ ]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.hstack((a4, a5, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# horizontal splitting

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# vertical splitting

In [ ]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [ ]:
np.vsplit(a5,2) # can't break into 2 equal parts

ValueError: ignored

In [ ]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]