**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
x = np.zeros(10, dtype=np.int_)
print(x)
x[5] = 1
print(x)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
import random
a = int(input("Enter a: "))
b = int(input("Enter b: "))

n = a*b
x = np.random.randint(n, size=(a,b))
print(x)

Enter a: 3
Enter b: 4
[[ 5  7  5  7]
 [11  3  3  6]
 [10  5  1  8]]


In [ ]:
a, b = map(int, input("Enter two Number: ").split())
x = np.random.random((a,b))
x

Enter two Number: 3 4


array([[0.68167858, 0.66822969, 0.23866944, 0.68802442],
       [0.93359835, 0.60326139, 0.36953907, 0.91651642],
       [0.57667207, 0.41509439, 0.25495184, 0.04943981]])

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
def one_():
  x = np.ones((5,5))
  print(x)
  x[1:4,1:4] = 0
  print(x)

one_()

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# not possible

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
x = np.zeros((5,5))
print(x)
x += np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
x = np.random.randint(1, 100, (10,2))
point = np.array([2,3])
print(x)

np.sqrt(np.sum((x - point)**2, axis =1)).astype(int)

[[78 41]
 [89 98]
 [39 62]
 [20 21]
 [63 76]
 [86 28]
 [83 83]
 [96 43]
 [27 33]
 [79 80]]


array([ 84, 128,  69,  25,  95,  87, 113, 102,  39, 108])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
x = np.arange(336).reshape(6,7,8)
x

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [ ]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
x = input().strip().split()
np.array(x[::-1], dtype= np.float32)

3 4 5 6 7      8


array([8., 7., 6., 5., 4., 3.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
a = np.array([1, 2])
a.size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
import numpy as np

def softmax(x):
    if isinstance(x, np.ndarray) and x.ndim == 1:
        exp_arr = np.exp(x)
        softmax_arr = exp_arr / np.sum(exp_arr)
        return softmax_arr
    else:
        raise ValueError("Input must be a numpy 1D array")

x = np.array([86.03331084, 37.7285648 , 48.64908087, 87.16563062, 38.40852563, 37.20006318])
result = softmax(x)
print(result)


[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def ver_stack(*args):
  for arr in args:
    if type(arr) != np.ndarray:
      raise ValueError("Input must be 1d array")
  return np.vstack(args)

a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2, -1)
print(b)
ver_stack(a,b)
c = np.random.random((2,5))
ver_stack(a,b,c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.53026531, 0.60852008, 0.86163731, 0.66091375, 0.07951131],
       [0.52530822, 0.5279288 , 0.533094  , 0.63253748, 0.44249509]])

In [ ]:
def vertical_stack(*args):
    arrays = []
    for arr in args:
        if isinstance(arr, np.ndarray):
            arrays.append(arr)
        else:
            raise ValueError("All inputs must be numpy arrays")

    return np.vstack(arrays)

vertical_stack(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
from datetime import datetime, timedelta

def date_array(start: str, end: str):
  if type(start) != str and type(end) != str:
    raise TypeError

  total_days_of_month = {'01': 31, '02': 28, '03': 31, '04': 30, '05': 31, '06': 30, '07': 31, '08': 31, '09': 30, '10': 31, '11': 30, '12': 31}

  end = end.split('-')
  end_last = int(end[-1]) + 1
  if total_days_of_month[end[-2]] < end_last:
    days_diff = end_last - total_days_of_month[end[-2]]
    end[-1] = f"0{days_diff}" if days_diff < 10 else f"{days_diff}"
    next_month = int(end[-2]) + 1
    end[-2] = f"0{next_month}" if next_month < 10 else f"{next_month}"
  else:
    end[-1] = f"0{end_last}" if end_last < 10 else f"{end_last}"
  end = "-".join(end)
  return np.arange(start, end, dtype="datetime64[D]")

date_array(start='2015-11-05', end='2015-11-30')

array(['2015-11-05', '2015-11-06', '2015-11-07', '2015-11-08',
       '2015-11-09', '2015-11-10', '2015-11-11', '2015-11-12',
       '2015-11-13', '2015-11-14', '2015-11-15', '2015-11-16',
       '2015-11-17', '2015-11-18', '2015-11-19', '2015-11-20',
       '2015-11-21', '2015-11-22', '2015-11-23', '2015-11-24',
       '2015-11-25', '2015-11-26', '2015-11-27', '2015-11-28',
       '2015-11-29', '2015-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
x = np.random.random((3,4))
print(x)
print(x.mean(axis=1, keepdims=True))
x - x.mean(axis=1, keepdims=True)

[[0.02259733 0.6649023  0.09655152 0.36101446]
 [0.19731781 0.90827019 0.95193197 0.93612793]
 [0.32117766 0.47007738 0.33924806 0.33628911]]
[[0.2862664 ]
 [0.74841197]
 [0.36669805]]


array([[-0.26366907,  0.37863589, -0.18971488,  0.07474806],
       [-0.55109416,  0.15985822,  0.20351999,  0.18771595],
       [-0.04552039,  0.10337933, -0.02744999, -0.03040895]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
a =  np.arange(12).reshape(3,4)
print(a)
a[:, [1,2]] = a[: , [2,1]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
def replace(a):
  a[a % 2 != 0] = -1
  return a

a = np.array([1,2,3,4,5,6,7,8,9,10])
replace(a)

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

print(a >b)
print(b < a)

b[a>b] = a[b<a]
print(a)
print(b)

[ True  True False False  True]
[ True  True False False  True]
[6 3 1 5 8]
[6 3 1 7 8]


In [ ]:
def max_array(arr1, arr2):
    result = np.maximum(arr1, arr2)
    return result

max_array(a, b)


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3931, 7686,   73, 5113, 2977],
       [7769, 5047, 2795, 3581, 3884],
       [3798,  767, 4213, 1318, 8019],
       [9315, 9660, 9449,  626, 9832],
       [8751, 6520, 2824, 3229, 2591],
       [9694, 8299, 3026, 5446, 5950],
       [4040, 6777, 1206, 1099, 1227],
       [5018, 4500, 5974,  683, 4960]])

In [ ]:
#Code here
arr1[:, ::2]


array([[3931,   73, 2977],
       [7769, 2795, 3884],
       [3798, 4213, 8019],
       [9315, 9449, 9832],
       [8751, 2824, 2591],
       [9694, 3026, 5950],
       [4040, 1206, 1227],
       [5018, 5974, 4960]])

In [ ]:
(arr1 - arr1.min()) / (arr1.max() - arr1.min())

array([[0.39532739, 0.78010042, 0.        , 0.51644636, 0.29757147],
       [0.78860539, 0.50968337, 0.27892202, 0.35946306, 0.39051132],
       [0.38169894, 0.07111384, 0.42422379, 0.12757455, 0.81422277],
       [0.94702326, 0.98237524, 0.96075418, 0.05666564, 1.        ],
       [0.88923045, 0.66062097, 0.28189364, 0.32339379, 0.25801824],
       [0.98585921, 0.84291423, 0.30259248, 0.55056871, 0.60221334],
       [0.40649657, 0.68695563, 0.11609796, 0.10513372, 0.11824982],
       [0.50671175, 0.45363254, 0.60467261, 0.0625064 , 0.50076852]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def largest_item(arr, n):
  if n > len(arr):
    raise IndexError("n is large")

  arr.sort()
  return arr[-n]

a = np.array([12,34,40, 7,1,0])
largest_item(a, 1)

40

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
b = np.repeat(a,3)
print(b)
c = np.tile(a,3)
print(c)
np.hstack([b,c])

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])